# Generated by Django 4.2.8 on 2024-02-09 12:15

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name=django.contrib.auth.models.AbstractUser)),
                ('password', models.CharField(max_length=16, verbose_name=django.contrib.auth.models.AbstractUser)),
                ('fullname', models.CharField(max_length=16, verbose_name='Fullname of user')),
                ('profile_picture', models.ImageField(upload_to='user-images/', verbose_name='Profile picture')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('followers', models.PositiveBigIntegerField(default=0, verbose_name="User's followers")),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
